### ISSUE TITLE
nice view

### ISSUE THREAD

**Issue by jjhesk** [sababado/CircularView#2]
can you use the finger to spin the wheel with fraction on it? that would be extra nice.

**Comment by sababado** [comment]
Do you mean use a built in function to start the wheel spin when tapping with your finger? If so, I'd rather not implement that in the library since there are so many ways to "spin the wheel".

In case you haven't seen it you can see the example in the [sample code](https://github.com/sababado/CircularView/blob/master/sample/src/main/java/com/sababado/circularview/sample/MainActivity.java#L40).

**Comment by jjhesk** [comment]
true. I will take a good look.

**Comment by sababado** [comment]
Great. Let me know if you have questions. If you can think of a way to improve it please let me know or feel free to create a pull request.
