### ISSUE TITLE
Is it possible to do a setOnItemLongClickListener instead of a regular onitemclick?

### ISSUE THREAD

**Issue by Ponpoorani** [sababado/CircularView#4]

**Comment by Ponpoorani** [comment]
@sababado Please let me know!

**Comment by sababado** [comment]
@Ponpoorani It should be doable!

The CircularView class overrides an `onTouchEvent` method. This would be the place to check for a long press.

[http://stackoverflow.com/a/7921439/657936](Potential Solution)

If you'd like to take a stab at it and create a pull request, be my guest. It'll be a few days before I could get it going.

**Comment by sababado** [comment]
Turns out I had a bit of time this afternoon to crunch this out. I hope this helps you!
TL;DR - In a few hours you can get version 1.1.0 from jcenter. (I didn't explicitly update maven central so I don't know if it will update there)

I ended up setting an OnLongClickListener inside of the circular view class. I need to do a bit of management to ensure that a click or a long click is processed correctly, however the result doesn't look to bad.
